service: aws-lambda-recaptcha

provider:
  name: aws
  runtime: nodejs6.10
  stage: development
  region: ap-northeast-1

plugins:
  - serverless-webpack

functions:
  recaptcha:
    handler: handler.recaptcha
    description: Lambda + Recaptcha (To prevent Abuse).
    memorySize: 1024
    timeout: 5
    events:
      - http:
          path: recaptcha
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
